description = "Embedded Web Server"
long-description = """

EWS is a web server construction kit, designed for embedded
applications using the GNAT Ada compiler.

The project is hosted at https://github.com/simonjwright/ews.

"""
name = "ews"
version = "1.11.0"
authors = ["Simon Wright <simon@pushface.org>"]
licenses = "GPL-3.0-only WITH GCC-exception-3.1"
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]
project-files = ["ews.gpr"]
tags = ["web", "server"]
website = "https://github.com/simonjwright/ews"

[[depends-on]]
xmlada = "any"

[gpr-externals]
LIBRARY_TYPE = ["relocatable", "static"]

[[actions]]
type = "post-build"
command = ["gprbuild", "-P", "generator/ews_generator.gpr"]

[environment]
PATH.append="${CRATE_ROOT}/bin"

[configuration]
disabled = true

[origin]
commit = "12c3dc3754ab724b371b46e6e00f64b5bbfe31f7"
url = "git+https://github.com/simonjwright/ews.git"

