description = "Tk (Tool Control Language Toolkit)"
name = "libtk"
licenses = "TCL"

authors = ["Simon Wright"]
maintainers = ["Simon Wright <simon@pushface.org>"]
maintainers-logins = ["simonjwright"]

[[external]]
kind="system"
[external.origin."case(distribution)"]
"debian|ubuntu" = ["tk-dev"]
"msys2" = ["mingw-w64-x86_64-tk"]
